name: Tests
on:
  push:
  schedule:
    - cron: '50 0 * * FRI' # Every Friday at 00:50 UTC (4:50pm Pacific)
jobs:
  run-tests:
    name: Run tests (Rust ${{ matrix.rust }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - "1.56.0"
          - stable
          - beta
          - nightly
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install Rust toolchain (${{ matrix.rust }})
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        default: true
        components: rustfmt,clippy
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run benchmarks
      run: cargo bench
    - name: Run Clippy
      run: cargo clippy
